 steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download functionapp pipeline artifact'
    inputs:
      artifact: askai-kminsight-$(Build.BuildNumber)

  - task: AzureFunctionApp@1
    displayName: 'Azure functions app deploy'
    inputs:
      azureSubscription:   ${{ parameters.service_conn }}
      appType: functionAppLinux
      appName: $(functionAppName)
      package: '$(Pipeline.Workspace)/askai-kminsight-$(Build.BuildNumber).zip'