name: 'KM_INSIGHT_$(Date:yyyyMMdd)$(Rev:.r)'
variables:
  vmImage: 'ubuntu-latest'
  location: 'canadaeast'

stages:
  - stage: BUILD
    jobs:
      - job: InitBuild
        displayName: 'Build'
        pool:
          vmImage: $(vmImage)
        steps:
          - template: build/init-build.yml

  - stage: DEPLOY
    dependsOn:
      - BUILD
    variables:
      - name: functionAppName
        value: $(KMInsightFuncName)
    jobs:
      - job: KMInsightDeploy
        displayName: 'Deploy KM Insight Deploy'
        pool:
          vmImage: $(vmImage)
        steps:
          - template: deploy/deploy-app.yml
            parameters:
              service_conn: $(service_connection)