### 1. Apply for Leave
POST https://psmartinvoke.azurewebsites.net/api/SmartInvoke
Content-Type: application/json

{
  "Query": "Apply leave for EMP4569 starting 2025-03-10 to 2025-03-12",
  "Language": "English",
  "UserId": "vscode"
  ,"IsShowPlanOnly": true
}

### 2. Apply for leave - insufficient info
POST https://psmartinvoke.azurewebsites.net/api/SmartInvoke
Content-Type: application/json

{
  "Query": "Apply leave",
  "Language": "English",
  "UserId": "vscode"
  ,"IsShowPlanOnly": true
}

### 3. Check Leave Status
POST https://psmartinvoke.azurewebsites.net/api/SmartInvoke
Content-Type: application/json

{
  "Query": "Check my leave balance for me EMP9871",
  "Language": "English",
  "UserId": "vscode"
  ,"IsShowPlanOnly": true
}

### 4. View Leave Types
POST https://psmartinvoke.azurewebsites.net/api/SmartInvoke

{
  "Query": "What are the types of leave available?",
  "Language": "English",
  "UserId": "vscode"
  ,"IsShowPlanOnly": true
}
